apiVersion: v1
kind: Service
metadata:
  name: {{ include "endpoint.fullname" . }}
  labels: {{- include "endpoint.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3008
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "endpoint.selectorLabels" . | nindent 4 }}
