apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workflow-engine.fullname" . }}-config
  labels: {{- include "workflow-engine.labels" . | nindent 4 }}
data:
  SERVICE_NAME: "workflow-engine"
  SERVICE_PORT: "3002"
  POSTGRES_HOST: {{ .Values.global.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.global.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.global.postgres.database | quote }}
  NATS_URL: {{ .Values.global.nats.url | quote }}
  ALLOWED_ORIGINS: {{ .Values.global.allowedOrigins | quote }}
