apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels: {{- include "frontend.labels" . | nindent 4 }}
data:
  SERVICE_NAME: "frontend"
  SERVICE_PORT: "80"
