apiVersion: v2
name: ems-cop
description: EMS-COP â€” Common Operating Picture
type: application
version: 0.12.0
appVersion: "0.12.0"

dependencies:
  - name: postgresql
    version: "~16.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: redis
    version: "~19.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
  - name: nats
    version: "~1.2"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
