apiVersion: v1
kind: Service
metadata:
  name: {{ include "c2-gateway.fullname" . }}
  labels: {{- include "c2-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "c2-gateway.selectorLabels" . | nindent 4 }}
