apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ws-relay.fullname" . }}-config
  labels: {{- include "ws-relay.labels" . | nindent 4 }}
data:
  SERVICE_NAME: "ws-relay"
  SERVICE_PORT: "3009"
  NATS_URL: {{ .Values.global.nats.url | quote }}
  ALLOWED_ORIGINS: {{ .Values.global.allowedOrigins | quote }}
