apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ws-relay.fullname" . }}-secrets
  labels: {{- include "ws-relay.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
