apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification.fullname" . }}-secrets
  labels: {{- include "notification.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.global.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  SMTP_USER: ""
  SMTP_PASS: ""
