apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification.fullname" . }}
  labels: {{- include "notification.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3007
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "notification.selectorLabels" . | nindent 4 }}
