apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit.fullname" . }}-secrets
  labels: {{- include "audit.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.global.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.global.clickhouse.password | quote }}
