apiVersion: v1
kind: Service
metadata:
  name: {{ include "audit.fullname" . }}
  labels: {{- include "audit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3006
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "audit.selectorLabels" . | nindent 4 }}
